name: TicTacToe

on:
  issues:
    types: [opened]

jobs:
  run_ttt_game:
    runs-on: ubuntu-latest
    
    # This 'if' condition checks the Issue Title for the command and restricts RESET to the owner.
    if: |
      github.event_name == 'issues' && 
      github.actor != 'github-actions[bot]' && 
      (
        contains(github.event.issue.title, 'TicTacToe: ') && !contains(github.event.issue.title, 'TicTacToe: RESET') ||
        (contains(github.event.issue.title, 'TicTacToe: RESET') && github.event.issue.user.login == 'madhavagarwal3012')
      )
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Tic-Tac-Toe Game Logic
        env:
          # Now uses the Issue Title for the command
          MOVE_COMMAND: ${{ github.event.issue.title }} 
          # Now uses the Issue Author for the actor check
          GITHUB_ACTOR: ${{ github.event.issue.user.login }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }} 
        run: python src/tictactoe.py

      - name: Commit and Push Changes (Update README and State)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Tic-Tac-Toe: new move processed"
          files: README.md data/ttt_state.json data/ttt_moves.txt
